import React from "react";
import Header from "./../Header/Header";
import Footer from "./../Footer/Footer";

import background from "./../../images/doughbgvidlow.mp4";
import dough from "./../../images/doughcolorful.svg";
import veDOUGH from "./../../images/veDOUGH.svg";
import buyDough from "./../../images/DOUGH2v.png";
import lock from "./../../images/lock.png";
import person from "./../../images/person-raising-hand.png";
import raisedHand from "./../../images/raised-hand.png";
import womanLaptop from "./../../images/woman-laptop.png";
import pirates from "./../../images/pirates.png";
import gem from "./../../images/gem.png";
import steak from "./../../images/steak.png";
import hourglass from "./../../images/hourglass.png";
import "./Home.css";

const Home = () => {
  return (
    <div>
      <Header />
      <div className="tab1">
        <video autoPlay muted loop>
          <source src={background} type="video/mp4" />
        </video>
        <div className="tab1-main">
          <h3>
            PieDAO’s <br /> Governance Token
          </h3>
          <img src={dough} alt="Dough" />
          <p>
            Contribute and be rewarded <br /> for building a better organization
            and products.
          </p>
          <div className="buy-dough">
            <img src={buyDough} alt="Buy Dough" />
            <div>
              <h4>Buy DOUGH</h4>
              <p>
                Current Price: <strong>$0.44</strong>
              </p>
            </div>
          </div>
          <a href="#">Stake DOUGH</a>
          <a className="buy-dough-metamask">Add to MetaMask 🦊</a>
        </div>
      </div>
      <div className="tab2">
        <div>
          <img src={hourglass} alt="" />
          <span>
            Long term <br /> alignment
          </span>
        </div>

        <div>
          <img src={gem} alt="" />
          <span>
            Rewarded <br /> commitment
          </span>
        </div>

        <div>
          <img src={pirates} alt="" />
          <span>
            Treasury revenues <br /> distribution
          </span>
        </div>

        <div>
          <img src={womanLaptop} alt="" />
          <span>
            The future of work <br /> is DAO
          </span>
        </div>

        <div>
          <img src={raisedHand} alt="" />
          <span>
            Hybrid governance <br /> beyond coin vote
          </span>
        </div>
      </div>
      <div className="tab3">
        <h2>A new governance model</h2>
        <br />
        <p>
          DOUGH is the basic element to start your journey and be part of the
          PieDAO family.
          <br />
          <br />
          If you stake DOUGH for a minimum of 6 months, you get in exchange
          veDOUGH, PieDAO’s governance token.
          <br />
          <br />
          With veDOUGH you can help the community steer the destiny of the DAO
          and its products, make proposals, vote on
          <br />
          issues while being compensated for your commitment and effort.
          <br />
          <br />
          In fact PieDAO redistributes 60% of the revenues generated by its
          products and treasury management to active
          <br />
          community members, proportionally to the amount of veDOUGH they hold.
          <br />
          <br />
        </p>
        <a href="#">Stake DOUGH</a>
      </div>
      <div className="tab4">
        <p> <img src={steak} alt="" /> Key Staking Stats</p>
        <div>
          <div>
            <img src={buyDough} alt="" />
            <p>
              Total staked DOUGH <strong>0.00 DOUGH</strong>
            </p>
            <div class="progress" data-label="44.92% of 27,74 M Tot circulating DOUGH">
              <span class="value"></span>
            </div>
          </div>
          <div>
            <img src={lock} alt="" />
            <p>
              Average Time Lock <strong> 34 Months</strong>
            </p>
          </div>
        </div>

        <div>
          <div>
            <img src={veDOUGH} alt="" />
            <p>
              Total veDOUGH <strong> 0.00 veDOUGH</strong>
            </p>
            <div class="progress yellow" data-label="5% Quorum = 610,237.70 veDOUGH">
              <span class="value value-100 yellow"></span>
            </div>
          </div>
          <div>
            <img src={person} alt="" />
            <p>
              Voting Addresses <strong> 322 </strong>
            </p>
          </div>
        </div>
      </div>
      <div className="tab5">
        <h2>Doughconomics</h2>
        <br />
        <p>
          This is how the DAO makes money and how is redistributing them to the
          system
        </p>
        <a href="#">Test your assumptions on the simulator ></a>
      </div>
      <Footer />
    </div>
  );
};

export default Home;
